[package]
name = "paradise_atmos_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
auxtools = { git = "https://github.com/Jerrody/auxtools" }
dashmap = "5.4.0"
once_cell = "1.17.0"

[profile.release]
lto = true
codegen-units = 1
